# Generated by Django 4.0.1 on 2023-01-03 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.BigIntegerField(verbose_name='id чата')),
                ('tg_user_id', models.BigIntegerField(unique=True, verbose_name='id пользователя')),
                ('tg_username', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Имя пользователя')),
                ('verification_code', models.CharField(max_length=15, unique=True, verbose_name='Код верификации')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
    ]
